[DEBUG][21-07-14][org.apache.ibatis.logging.LogFactory]Logging initialized using 'class org.apache.ibatis.logging.log4j.Log4jImpl' adapter.
[DEBUG][21-07-14][org.apache.ibatis.logging.LogFactory]Logging initialized using 'class org.apache.ibatis.logging.log4j.Log4jImpl' adapter.
[DEBUG][21-07-14][org.apache.ibatis.datasource.pooled.PooledDataSource]PooledDataSource forcefully closed/removed all connections.
[DEBUG][21-07-14][org.apache.ibatis.datasource.pooled.PooledDataSource]PooledDataSource forcefully closed/removed all connections.
[DEBUG][21-07-14][org.apache.ibatis.datasource.pooled.PooledDataSource]PooledDataSource forcefully closed/removed all connections.
[DEBUG][21-07-14][org.apache.ibatis.datasource.pooled.PooledDataSource]PooledDataSource forcefully closed/removed all connections.
[DEBUG][21-07-14][org.apache.ibatis.transaction.jdbc.JdbcTransaction]Opening JDBC Connection
[DEBUG][21-07-14][org.apache.ibatis.datasource.pooled.PooledDataSource]Created connection 931675031.
[DEBUG][21-07-14][org.apache.ibatis.transaction.jdbc.JdbcTransaction]Setting autocommit to false on JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@37883b97]
[DEBUG][21-07-14][cn.edu.xidian.dao.UserMapper.getUserById]==>  Preparing: SELECT * FROM mybatis.user WHERE user_id = ? 
[DEBUG][21-07-14][cn.edu.xidian.dao.UserMapper.getUserById]==> Parameters: 1(Integer)
[DEBUG][21-07-14][cn.edu.xidian.dao.UserMapper.getUserById]<==      Total: 1
[DEBUG][21-07-14][org.apache.ibatis.transaction.jdbc.JdbcTransaction]Resetting autocommit to true on JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@37883b97]
[DEBUG][21-07-14][org.apache.ibatis.transaction.jdbc.JdbcTransaction]Closing JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@37883b97]
[DEBUG][21-07-14][org.apache.ibatis.datasource.pooled.PooledDataSource]Returned connection 931675031 to pool.
[DEBUG][21-07-14][org.apache.ibatis.logging.LogFactory]Logging initialized using 'class org.apache.ibatis.logging.log4j.Log4jImpl' adapter.
[DEBUG][21-07-14][org.apache.ibatis.logging.LogFactory]Logging initialized using 'class org.apache.ibatis.logging.log4j.Log4jImpl' adapter.
[DEBUG][21-07-14][org.apache.ibatis.datasource.pooled.PooledDataSource]PooledDataSource forcefully closed/removed all connections.
[DEBUG][21-07-14][org.apache.ibatis.datasource.pooled.PooledDataSource]PooledDataSource forcefully closed/removed all connections.
[DEBUG][21-07-14][org.apache.ibatis.datasource.pooled.PooledDataSource]PooledDataSource forcefully closed/removed all connections.
[DEBUG][21-07-14][org.apache.ibatis.datasource.pooled.PooledDataSource]PooledDataSource forcefully closed/removed all connections.
[DEBUG][21-07-14][org.apache.ibatis.transaction.jdbc.JdbcTransaction]Opening JDBC Connection
[DEBUG][21-07-14][org.apache.ibatis.datasource.pooled.PooledDataSource]Created connection 931675031.
[DEBUG][21-07-14][org.apache.ibatis.transaction.jdbc.JdbcTransaction]Setting autocommit to false on JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@37883b97]
[DEBUG][21-07-14][cn.edu.xidian.dao.UserMapper.getUserById]==>  Preparing: SELECT * FROM mybatis.user WHERE user_id = ? 
[DEBUG][21-07-14][cn.edu.xidian.dao.UserMapper.getUserById]==> Parameters: 1(Integer)
[DEBUG][21-07-14][cn.edu.xidian.dao.UserMapper.getUserById]<==      Total: 1
[DEBUG][21-07-14][org.apache.ibatis.transaction.jdbc.JdbcTransaction]Resetting autocommit to true on JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@37883b97]
[DEBUG][21-07-14][org.apache.ibatis.transaction.jdbc.JdbcTransaction]Closing JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@37883b97]
[DEBUG][21-07-14][org.apache.ibatis.datasource.pooled.PooledDataSource]Returned connection 931675031 to pool.
[INFO][21-07-14][cn.edu.xidian.dao.UserMapperTest]info:进入了info log4jTest
[DEBUG][21-07-14][cn.edu.xidian.dao.UserMapperTest]debug:进入了debug方式
[ERROR][21-07-14][cn.edu.xidian.dao.UserMapperTest]error:进入了error方式
[INFO][21-07-14][cn.edu.xidian.dao.UserMapperTest]info:进入了info log4jTest
[DEBUG][21-07-14][cn.edu.xidian.dao.UserMapperTest]debug:进入了debug方式
[ERROR][21-07-14][cn.edu.xidian.dao.UserMapperTest]error:进入了error方式
